version: '3'
services:
  digi-postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    volumes:
      - /var/folders/data:/var/lib/postgresql/data
  mafia-app:
    image: mafia-app
    ports:
      - 8000:80
    depends_on:
      - digi-postgres
